---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	intent_classifier_node(intent_classifier_node)
	title_router_node(title_router_node)
	merge_filters_node(merge_filters_node)
	search_vector_node(search_vector_node)
	hydratation_node(hydratation_node)
	validation_node(validation_node)
	validation_film_node(validation_film_node)
	format_cards_node(format_cards_node)
	card_node(card_node)
	load_film_node(load_film_node)
	verif_film_node(verif_film_node)
	wikipedia_search_node(wikipedia_search_node)
	synthesis_node(synthesis_node)
	narrator_node(narrator_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> intent_classifier_node;
	card_node --> narrator_node;
	format_cards_node --> narrator_node;
	hydratation_node --> validation_node;
	intent_classifier_node -. &nbsp;Load_film_node&nbsp; .-> load_film_node;
	intent_classifier_node -.-> narrator_node;
	intent_classifier_node -. &nbsp;route_after_title_check&nbsp; .-> title_router_node;
	load_film_node -.-> merge_filters_node;
	load_film_node -. &nbsp;route_after_title_check&nbsp; .-> title_router_node;
	load_film_node -.-> verif_film_node;
	merge_filters_node --> search_vector_node;
	search_vector_node -. &nbsp;Affichage_film_unique&nbsp; .-> hydratation_node;
	search_vector_node -. &nbsp;Merge_filters_node&nbsp; .-> merge_filters_node;
	search_vector_node -.-> narrator_node;
	search_vector_node -. &nbsp;Affichage_films&nbsp; .-> validation_film_node;
	synthesis_node --> narrator_node;
	title_router_node -. &nbsp;filter_and_search_hybrid&nbsp; .-> merge_filters_node;
	title_router_node -. &nbsp;direct_movie_detail&nbsp; .-> search_vector_node;
	validation_film_node -.-> card_node;
	validation_film_node -.-> format_cards_node;
	validation_film_node -. &nbsp;Merge_filters_node&nbsp; .-> merge_filters_node;
	validation_film_node -.-> narrator_node;
	validation_film_node -.-> synthesis_node;
	validation_film_node -.-> wikipedia_search_node;
	validation_node -.-> card_node;
	validation_node -.-> format_cards_node;
	validation_node -.-> narrator_node;
	validation_node -. &nbsp;Search_vector_node&nbsp; .-> search_vector_node;
	validation_node -.-> synthesis_node;
	validation_node -.-> wikipedia_search_node;
	verif_film_node -.-> narrator_node;
	verif_film_node -.-> wikipedia_search_node;
	wikipedia_search_node -.-> card_node;
	wikipedia_search_node -.-> format_cards_node;
	wikipedia_search_node -.-> narrator_node;
	wikipedia_search_node -.-> synthesis_node;
	narrator_node --> __end__;
	search_vector_node -. &nbsp;Search_vector_node&nbsp; .-> search_vector_node;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
